package com.medicalrecord.domain.entity;

public enum Specialty {
    ANATOMICAL_PATHOLOGY, ANESTHESIOLOGY,  CARDIOLOGY, CARDIOVASCULAR, CLINICAL_IMMUNOLOGY, CLINICAL_ALLERGY, DERMATOLOGY,
    EMERGENCY_MEDICINE, ENDOCRINOLOGY, GASTROENTEROLOGY, GENERAL_INTERNAL_MEDICINE, GENERAL_SURGERY, GENERAL_PATHOLOGY,
    GERIATRIC_MEDICINE, HEMATOLOGY, MEDICAL_BIOCHEMISTRY, ONCOLOGY, NEPHROLOGY, NEUROLOGY, NEUROSURGERY, GYNECOLOGY,
    ORTHOPEDIC_SURGERY, PEDIATRICS, PLASTIC_SURGERY, PSYCHIATRY, RESPIROLOGY, UROLOGY
}
